Revert change made in #207, and the alpine change in #206.
Installing and using AWS-cli in Jammy seems to be broken somehow, getting this error:

>  fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

I assume that it's a permission thing in S3 (not sure how it's acting different in a different image), but it's something I'll have to fix later. Revert to a working state.