Make a single JAR with all deps
Using the `maven-shade-plugin`. Necessary becasue:

* No longer have to list all jars on the classpath when running any command
* Means it's easier (and normal) to be able to run commands with `java`
* can remove all maven exec commands, and not rely on the maven setup in production
    * all commands become java -jar target/efspserver-with-deps.jar ...
    * easier to pass args
    * don't need to possible have to download more maven deps in PROD

The shade plugin config does 3 things specifically:

* sets the default main class (i.e. the EfspServer)
* keeps all of the contents of `bus-extensions.txt` files instead of
  overwriting each
    * necessary to be able to find all of the CXF WSDL stuff at runtime
* filters to handle signed jars: the JVM complains if they are still present
    * something like this:
      ```
      Error: A JNI error has occurred, please check your installation and try again
      Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
      ```

See this stackoverflow answer for more info: https://stackoverflow.com/a/68743972/11416267.